### ISSUE TITLE
jira bug 21.1

### ISSUE THREAD

**Issue by maxAtSW** [Cyberark-workato-dev/conjur#30]
##description
Steps to reproduce:

Current Results:

Expected Results:

Error Messages:

Logs:

Other Symptoms:

Tenant ID / Pod Number:

##Found in version
10.10.3

##Workaround Complexity
No need to apply a workaround (disabled)

##Workaround Description
asd

##Link to JIRA bug
https://ca-il-jira-test.il.cyber-ark.com/browse/ONYX-6472

**Comment by maxAtSW** [comment]
//Author: Avigad.Maoz@cyberark.com

jira

**Comment by avigadmaoz** [comment]
git
